/**
 * English wording for everything the app *emits*: the Markdown outline, the CSV,
 * the AI prompts, the answer-first synthesis document, the native PPTX slide,
 * and the print / presentation surfaces.
 *
 * An export is a deliverable, so it follows the reader's language exactly like
 * the screen does. Two things follow from that:
 *
 * - **Section markers round-trip.** `synthesise()` writes the synthesis document
 *   and `formatSynthesis()` parses it back into typed lines. Both read `markers`
 *   from here, so translating one can never desynchronise the other. That is why
 *   those entries carry their Markdown emphasis (`**Answer:**`): the marker is
 *   one string with one owner, not a prefix rebuilt in two files.
 * - **Machine-facing values stay machine-facing.** The CSV's *header row* is
 *   prose and lives here; its *cells* keep the raw enum keys (`formula`, `pass`)
 *   so a spreadsheet formula written against an English export still works
 *   against a Danish one. Same for the compact `_[type · ME:x · CE:y]_`
 *   annotation: the whole annotation is one entry, so a locale *may* reword it,
 *   but English renders the raw states it always has.
 */
import type { CheckState, DecompositionType } from '@/domain/types';
import { LOCALE, num, plur, quote } from './_locale';

/** A node's numeric value with its (user-typed) unit — "100 M DKK" / "42". */
const valueText = ({ amount, unit }: { amount: number; unit?: string }): string =>
  unit ? `${num(amount)} ${unit}` : `${num(amount)}`;

/** The axis a split is cut on, as an inline phrase — "by geography". */
const byDimension = ({ dimension }: { dimension: string }): string => `by ${dimension}`;

/**
 * The synthesis document's own structure, in words: the storyline section
 * markers and the prefixes that introduce a supporting-detail line. Written by
 * `domain/synthesis.ts`, matched by `domain/synthesisFormat.ts` — one copy, so
 * the writer and the parser cannot drift apart in any language.
 */
const markers = {
  situation: '**Situation:**',
  complication: '**Complication:**',
  answer: '**Answer:**',
  verdict: 'Verdict:',
  value: 'value:',
  rollUp: 'rolls up to',
  sensitivity: 'most sensitive to:',
  evidence: 'evidence:',
};

/** The standalone one-page HTML answer: its `<html lang>`, title, and sign-off. */
const answerPage = {
  lang: LOCALE,
  /** Fallback `<title>` when the tree's root question is empty. */
  title: 'MECE Studio answer',
  footer: 'Answer-first synthesis · generated by MECE Studio',
};

/**
 * CSV column headings. The column *order* lives in `services/exporters/csv.ts`;
 * only the words live here, so a translation can never shuffle the columns.
 */
const csvColumns = {
  path: 'path',
  label: 'label',
  decomposition: 'decomposition',
  exclusive: 'ME',
  exhaustive: 'CE',
  priority: 'priority',
  status: 'status',
  amount: 'amount',
  unit: 'unit',
  operator: 'operator',
};

export const exports = {
  /** Shared value / axis phrasing — outline, print, presentation, PPTX slide. */
  valueText,
  valueSuffix: (value: { amount: number; unit?: string }) => ` (${valueText(value)})`,
  byDimension,

  /** Markdown outline (Copy as Markdown). */
  priorityTag: ({ level }: { level: string }) =>
    `${level.charAt(0).toUpperCase()}${level.slice(1)} priority`,
  meceNote: ({
    type,
    dimension,
    exclusive,
    exhaustive,
  }: {
    type: DecompositionType;
    // Explicitly `| undefined`: the caller reads `split.dimension`, which is an
    // optional field, and `exactOptionalPropertyTypes` keeps "absent" and
    // "present but undefined" distinct.
    dimension?: string | undefined;
    exclusive: CheckState;
    exhaustive: CheckState;
  }) =>
    `  _[${type}${dimension ? ` ${byDimension({ dimension })}` : ''} · ME:${exclusive} · CE:${exhaustive}]_`,

  /** Ready-to-paste prompts the user runs in their own AI tool. */
  aiCritique: ({ tree }: { tree: string }) =>
    [
      'You are a McKinsey-style problem-solving coach. Below is an issue tree in',
      'Markdown — each decomposition is annotated with its MECE status (ME = mutually',
      'exclusive, CE = collectively exhaustive).',
      '',
      'Critique it:',
      '1. For each split, is it genuinely MECE? Call out overlaps (not ME) and gaps (not CE).',
      '2. Are the branches framed as sharp, testable issues — and are the right ones prioritised?',
      "3. What's missing, redundant, or mis-framed? Reference node labels.",
      '',
      'Tree:',
      '',
      tree,
    ].join('\n'),
  aiDecompose: ({ label, tree }: { label: string; tree: string }) =>
    [
      'You are a McKinsey-style problem-solving coach. Below is an issue tree in Markdown.',
      `Propose a MECE decomposition for the node ${quote(label)}: 2–5 mutually exclusive,`,
      'collectively exhaustive sub-issues (short labels), and name the single dimension you',
      'split on. Keep it consistent with the rest of the tree.',
      '',
      'Return ONLY the sub-issues as a Markdown bullet list — one per line, indented to nest —',
      'so they can be pasted straight back into the tool. For example:',
      '- First sub-issue',
      '- Second sub-issue',
      '  - a nested detail',
      '',
      'Tree:',
      '',
      tree,
      '',
      `Node to decompose: ${quote(label)}`,
    ].join('\n'),

  /** Storyline markers + detail-line prefixes (see the const above). */
  markers,

  /** The rolled-up verdict on the governing answer. */
  verdictLine: ({ parts, stance }: { parts: string[]; stance: string }) =>
    `${markers.verdict} ${parts.join(', ')} — ${stance}.`,
  verdictBranches: ({ supported, total }: { supported: number; total: number }) =>
    `${num(supported)} of ${num(total)} top branches supported`,
  verdictRefuted: ({ count }: { count: number }) => `${num(count)} refuted`,
  verdictParked: ({ count }: { count: number }) => `${num(count)} parked`,
  /** How the tested branches add up — `synthesis.ts` picks, this words it. */
  verdictStance: {
    holds: 'the answer holds',
    partial: 'the answer partially holds',
    doubt: 'the answer is in doubt',
    open: 'still open',
  },

  /** The synthesis body: where to start, then each branch and its numbers. */
  synthLead: ({ label }: { label: string }) => `Start with **${label}** — highest impact × ease.`,
  synthLeadTip: 'Tip: set impact × ease on the branches to rank where to start.',
  synthNoBranches: '_(No branches yet — decompose the question to begin.)_',
  synthDimension: ({ dimension }: { dimension: string }) => ` _[${byDimension({ dimension })}]_`,
  synthMeceFlags: ({ overlap, gap }: { overlap: boolean; gap: boolean }) =>
    `  ⚠ ${[overlap ? 'overlap' : '', gap ? 'gap' : ''].filter(Boolean).join(' + ')}`,
  synthValue: (value: { amount: number; unit?: string }) => `${markers.value} ${valueText(value)}`,
  synthRollUp: ({ value }: { value: number }) => `${markers.rollUp} ${num(value)}`,
  synthSensitivity: ({ label }: { label: string }) => `${markers.sensitivity} ${label}`,
  synthEvidence: ({ items }: { items: string[] }) => `${markers.evidence} ${items.join('; ')}`,

  /** The standalone one-page HTML answer (see the const above). */
  answerPage,

  /** CSV column headings (see the const above). */
  csvColumns,

  /** Print preview — the overlay chrome and the paper's status line. */
  printTitle: 'Print preview',
  printAction: 'Print',
  printClose: 'Close',
  printNotDecomposed: 'Not decomposed yet',
  printClean: 'MECE clean — no splits flagged',
  printToReview: ({ count }: { count: number }) =>
    `${num(count)} ${plur(count, { one: 'split', other: 'splits' })} to review`,

  /** Step-through presentation. */
  presentHeader: 'MECE Studio · Presentation',
  presentExit: 'Exit (Esc)',
  presentExitLabel: 'Exit presentation',
  /** Shown above an undecomposed node, where a tree-kind label would go. */
  presentNodeKind: 'Issue',
  presentLeaf: 'A leaf issue — no decomposition.',
  presentClean: 'MECE clean',
  presentProgress: ({ index, total }: { index: number; total: number }) =>
    `${num(index)} / ${num(total)}`,
  presentNavHint: '← / → to navigate · Esc to exit',
  presentPrev: '← Prev',
  presentNext: 'Next →',
};
