import { priorityBand } from '@/domain/priority';
import { childrenOf, splitOf } from '@/domain/tree';
import type { IssueTreeDoc, NodeId } from '@/domain/types';
import type { EditorMessages } from '@/i18n/types';

/** Quote a CSV cell when it contains a comma, quote, or newline (RFC 4180). */
function csvCell(value: string | number | undefined): string {
  const s = value === undefined ? '' : String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/**
 * A cell that opens like a spreadsheet formula. Excel, LibreOffice and Sheets
 * all evaluate a field starting with one of these, so a label such as
 * `=HYPERLINK("http://…")` would run on open rather than read as text.
 */
const FORMULA_START = /^[=+\-@\t\r]/;

/**
 * Defuse a **free-text** cell so a spreadsheet reads it as text, not a formula.
 *
 * Trees travel: they are exported to JSON, imported, and saved as templates, so
 * a label can easily be someone else's text by the time it reaches this
 * exporter. The prefix is a single quote, the conventional escape, and it is
 * applied only when the cell would otherwise start a formula.
 *
 * Deliberately **not** applied to the amount column: a leading `-` there is a
 * negative number, and defusing it would break the numeric handoff that is the
 * whole point of the export. Those cells are generated by us from a `number`,
 * never free text, so they cannot carry a payload.
 */
function csvText(value: string): string {
  return FORMULA_START.test(value) ? `'${value}` : value;
}

/** The column order. The words come from the catalogue; the order lives here. */
function headerRow(m: EditorMessages): string[] {
  const c = m.exports.csvColumns;
  return [
    c.path,
    c.label,
    c.decomposition,
    c.exclusive,
    c.exhaustive,
    c.priority,
    c.status,
    c.amount,
    c.unit,
    c.operator,
  ];
}

/**
 * Export the tree as CSV — one row per node — so the value model (amounts,
 * units, roll-up operator) and the analysis (decomposition, ME/CE state,
 * priority band, hypothesis status) land in a spreadsheet without retyping.
 * Pure; the natural handoff for a value-driver tree. Excel opens .csv directly.
 *
 * The **header row** is prose and follows the reader's language. The **cells**
 * deliberately do not: they carry the raw enum keys and unformatted numbers, so
 * a pivot table or formula written against one export keeps working against the
 * same tree exported in another language.
 */
export function treeToCsv(doc: IssueTreeDoc, m: EditorMessages): string {
  const rows: string[][] = [headerRow(m)];

  const walk = (id: NodeId, parentPath: string): void => {
    const node = doc.nodes[id];
    if (!node) return;
    const split = splitOf(doc, id);
    const path = parentPath ? `${parentPath} > ${node.label}` : node.label;
    rows.push([
      // The three free-text columns carry user (or imported) prose, so they are
      // the only ones that need defusing; the rest are enum keys and numbers we
      // generate ourselves.
      csvText(path),
      csvText(node.label),
      split?.decomposition ?? '',
      split ? split.mece.exclusive.state : '',
      split ? split.mece.exhaustive.state : '',
      node.priority ? priorityBand(node.priority) : '',
      node.status,
      node.value?.amount !== undefined ? String(node.value.amount) : '',
      csvText(node.value?.unit ?? ''),
      split?.operator ?? '',
    ]);
    for (const child of childrenOf(doc, id)) walk(child.id, path);
  };

  walk(doc.rootId, '');
  return `${rows.map((r) => r.map(csvCell).join(',')).join('\r\n')}\r\n`;
}
